name: tic_tac_toe
description: An AngularDart application -- Tic-Tac-Toe! Two-player only.
version: 0.0.4

environment:
  sdk: '>=1.23.0 <2.0.0'

dependencies:
  angular: ^4.0.0
  angular_components: ^0.8.0
  logging: any
  intl: any

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.3

transformers:
- angular:
    entry_points: web/main.dart
- $dart2js:
    checked: false
    minify: true
    commandLineOptions:
      - --dump-info
      - --trust-type-annotations
      - --trust-primitives
- dart_to_js_script_rewriter

#web:
#  compiler:
#    debug: dartdevc